name: tfgrid-erpnext
version: "1.0.0"
description: Open-source ERP system (Frappe/ERPNext)

patterns:
  recommended: single-vm
  supported:
    - single-vm

resources:
  cpu:
    min: 2
    recommended: 4
  memory:
    min: 4096
    recommended: 8192
  disk:
    min: 50
    recommended: 100
  ports:
    - 22:ssh
    - 80:http
    - 443:https

hooks:
  setup: deployment/setup.sh
  configure: deployment/configure.sh
  healthcheck: deployment/healthcheck.sh

environment:
  # Domain Configuration
  - name: DOMAIN
    required: true
    description: "Public domain for ERPNext (e.g., erp.example.com)"
  - name: SSL_EMAIL
    required: false
    description: "Email for Let's Encrypt SSL certificates"
    
  # DNS Automation (name.com and cloudflare recommended for full automation)
  - name: DNS_PROVIDER
    required: false
    description: "DNS provider for automatic A record setup"
    options:
      - manual
      - name.com
      - cloudflare
      - namecheap  # Requires manual IP whitelisting in Namecheap dashboard
    default: "manual"
  - name: NAMECOM_USERNAME
    required: false
    description: "Name.com username"
    depends_on:
      DNS_PROVIDER: "name.com"
  - name: NAMECOM_API_TOKEN
    required: false
    secret: true
    description: "Name.com API token"
    depends_on:
      DNS_PROVIDER: "name.com"
  - name: CLOUDFLARE_API_TOKEN
    required: false
    secret: true
    description: "Cloudflare API token"
    depends_on:
      DNS_PROVIDER: "cloudflare"
  - name: NAMECHEAP_API_USER
    required: false
    description: "Namecheap API username (requires IP whitelisting - not fully automated)"
    depends_on:
      DNS_PROVIDER: "namecheap"
  - name: NAMECHEAP_API_KEY
    required: false
    secret: true
    description: "Namecheap API key (requires IP whitelisting - not fully automated)"
    depends_on:
      DNS_PROVIDER: "namecheap"
      
  # ERPNext Configuration
  - name: SITE_NAME
    required: false
    description: "ERPNext site name (default: derived from domain)"
  - name: ADMIN_PASSWORD
    required: false
    secret: true
    description: "Admin password (auto-generated if not set)"
  - name: ERPNEXT_VERSION
    required: false
    description: "ERPNext version"
    default: "latest"
    
  # Company Setup (for initial wizard)
  - name: COMPANY_NAME
    required: false
    description: "Company name for initial setup"
  - name: COMPANY_ABBR
    required: false
    description: "Company abbreviation (e.g., ACME)"
  - name: COUNTRY
    required: false
    description: "Country for localization"
    default: "United States"
  - name: CURRENCY
    required: false
    description: "Default currency"
    default: "USD"
  - name: TIMEZONE
    required: false
    description: "Server timezone"
    default: "America/New_York"
    
  # Database Configuration
  - name: DB_PASSWORD
    required: false
    secret: true
    description: "MariaDB password (auto-generated if not set)"
  - name: DB_ROOT_PASSWORD
    required: false
    secret: true
    description: "MariaDB root password (auto-generated if not set)"
    
  # Performance
  - name: WORKER_COUNT
    required: false
    description: "Number of background workers"
    default: "2"
  - name: GUNICORN_WORKERS
    required: false
    description: "Number of Gunicorn workers"
    default: "4"
    
  # Backup Configuration
  - name: BACKUP_RETENTION_DAYS
    required: false
    description: "Number of days to keep backups"
    default: "30"

commands:
  backup:
    script: /opt/erpnext/scripts/backup.sh
    description: "Create site backup"
    args: "[--site sitename]"
  restore:
    script: /opt/erpnext/scripts/restore.sh
    description: "Restore site from backup"
    args: "--backup /path/to/backup"
  list-backups:
    script: /opt/erpnext/scripts/list-backups.sh
    description: "List available backups"
  logs:
    script: /opt/erpnext/scripts/logs.sh
    description: "View ERPNext logs"
    args: "[frontend|backend|scheduler|worker|db|redis] [--follow]"
  shell:
    script: /opt/erpnext/scripts/shell.sh
    description: "Open bench console"
  bench:
    script: /opt/erpnext/scripts/bench.sh
    description: "Run bench commands"
    args: "<bench-command>"
  migrate:
    script: /opt/erpnext/scripts/migrate.sh
    description: "Run database migrations"
  restart:
    script: /opt/erpnext/scripts/restart.sh
    description: "Restart ERPNext services"

status:
  check_interval: 60
  endpoints:
    - path: /api/method/ping
      expected_status: 200

logging:
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

tags:
  - erpnext
  - erp
  - frappe
  - business
  - accounting
  - inventory
  - docker
  - caddy
